import { researchCatalogSchema } from "./schema";

const rawCatalog = {
  universities: [
    {
      id: "university-imperial",
      name: "Imperial College London",
      countryCode: "GB",
      websiteUrl: "https://www.imperial.ac.uk/",
      aliases: ["Imperial"],
    },
    {
      id: "university-edinburgh",
      name: "The University of Edinburgh",
      countryCode: "GB",
      websiteUrl: "https://www.ed.ac.uk/",
      aliases: ["Edinburgh"],
    },
    {
      id: "university-ucl",
      name: "University College London",
      countryCode: "GB",
      websiteUrl: "https://www.ucl.ac.uk/",
      aliases: ["UCL"],
    },
    {
      id: "university-chulalongkorn",
      name: "Chulalongkorn University",
      countryCode: "TH",
      websiteUrl: "https://www.chula.ac.th/",
      aliases: ["Chula"],
    },
    {
      id: "university-kmutt",
      name: "King Mongkut's University of Technology Thonburi",
      countryCode: "TH",
      websiteUrl: "https://www.kmutt.ac.th/",
      aliases: ["KMUTT"],
    },
    {
      id: "university-mahidol",
      name: "Mahidol University",
      countryCode: "TH",
      websiteUrl: "https://www.mahidol.ac.th/",
    },
    {
      id: "university-georgia-tech",
      name: "Georgia Institute of Technology",
      countryCode: "US",
      websiteUrl: "https://www.gatech.edu/",
      aliases: ["Georgia Tech"],
    },
    {
      id: "university-mit",
      name: "Massachusetts Institute of Technology",
      countryCode: "US",
      websiteUrl: "https://web.mit.edu/",
      aliases: ["MIT"],
    },
    {
      id: "university-stanford",
      name: "Stanford University",
      countryCode: "US",
      websiteUrl: "https://www.stanford.edu/",
    },
    {
      id: "university-berkeley",
      name: "University of California, Berkeley",
      countryCode: "US",
      websiteUrl: "https://www.berkeley.edu/",
      aliases: ["UC Berkeley", "Berkeley"],
    },
  ],
  programs: [
    {
      id: "program-imperial-computing-beng",
      universityId: "university-imperial",
      name: "Computing BEng",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.imperial.ac.uk/study/courses/undergraduate/computing-beng/",
    },
    {
      id: "program-edinburgh-artificial-intelligence-bsc",
      universityId: "university-edinburgh",
      name: "Artificial Intelligence BSc (Hons)",
      degreeLevel: "bachelor",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://study.ed.ac.uk/programmes/undergraduate/388-artificial-intelligence",
    },
    {
      id: "program-edinburgh-artificial-intelligence-msc",
      universityId: "university-edinburgh",
      name: "Artificial Intelligence MSc",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://study.ed.ac.uk/programmes/postgraduate-taught/107-artificial-intelligence",
    },
    {
      id: "program-ucl-computer-science-bsc",
      universityId: "university-ucl",
      name: "Computer Science BSc",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-bsc",
    },
    {
      id: "program-chulalongkorn-computer-engineering-beng",
      universityId: "university-chulalongkorn",
      name: "Bachelor of Engineering: Computer Engineering (CP)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Engineering",
      officialUrl: "https://www.cp.eng.chula.ac.th/en/prospective/bachelor",
    },
    {
      id: "program-chulalongkorn-csit-msc",
      universityId: "university-chulalongkorn",
      name: "Master of Science Program in Computer Science and Information Technology",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.chula.ac.th/program/computer-science-and-information-technology",
    },
    {
      id: "program-kmutt-computer-science-bsc",
      universityId: "university-kmutt",
      name: "Bachelor of Science in Computer Science (English Program)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.sit.kmutt.ac.th/en/bsc/bsc-cs-2",
    },
    {
      id: "program-kmutt-computer-science-msc",
      universityId: "university-kmutt",
      name: "Master of Science in Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.sit.kmutt.ac.th/en/msc/msc-cs",
    },
    {
      id: "program-mahidol-computer-science-msc",
      universityId: "university-mahidol",
      name: "Master of Science in Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.ict.mahidol.ac.th/en/programs/comscience",
    },
    {
      id: "program-georgia-tech-computer-science-bs",
      universityId: "university-georgia-tech",
      name: "Bachelor of Science in Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://catalog.gatech.edu/programs/computer-science-bs",
    },
    {
      id: "program-mit-artificial-intelligence-decision-making-bs",
      universityId: "university-mit",
      name: "Bachelor of Science in Artificial Intelligence and Decision Making (Course 6-4)",
      degreeLevel: "bachelor",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://catalog.mit.edu/schools/mit-schwarzman-college-computing/electrical-engineering-computer-science/",
    },
    {
      id: "program-mit-computer-science-engineering-bs",
      universityId: "university-mit",
      name: "Bachelor of Science in Computer Science and Engineering (Course 6-3)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://catalog.mit.edu/schools/mit-schwarzman-college-computing/electrical-engineering-computer-science/",
    },
    {
      id: "program-stanford-computer-science-bs",
      universityId: "university-stanford",
      name: "Computer Science Bachelor's Program",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.cs.stanford.edu/academics-overview/academics-bachelors-program",
    },
    {
      id: "program-berkeley-computer-science-ba",
      universityId: "university-berkeley",
      name: "Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://undergraduate.catalog.berkeley.edu/programs/A5201U",
    },
  ],
};

export const researchCatalog = researchCatalogSchema.parse(rawCatalog);
