import { researchCatalogSchema } from "./schema";

const rawCatalog = {
  universities: [
    {
      id: "university-ku-leuven",
      name: "KU Leuven",
      countryCode: "BE",
      websiteUrl: "https://www.kuleuven.be/english/",
    },
    {
      id: "university-mcgill",
      name: "McGill University",
      countryCode: "CA",
      websiteUrl: "https://www.mcgill.ca/",
    },
    {
      id: "university-alberta",
      name: "University of Alberta",
      countryCode: "CA",
      websiteUrl: "https://www.ualberta.ca/",
      aliases: ["UAlberta"],
    },
    {
      id: "university-ubc",
      name: "University of British Columbia",
      countryCode: "CA",
      websiteUrl: "https://www.ubc.ca/",
      aliases: ["UBC"],
    },
    {
      id: "university-toronto",
      name: "University of Toronto",
      countryCode: "CA",
      websiteUrl: "https://www.utoronto.ca/",
      aliases: ["U of T", "UofT"],
    },
    {
      id: "university-waterloo",
      name: "University of Waterloo",
      countryCode: "CA",
      websiteUrl: "https://uwaterloo.ca/",
      aliases: ["Waterloo"],
    },
    {
      id: "university-rwth-aachen",
      name: "RWTH Aachen University",
      countryCode: "DE",
      websiteUrl: "https://www.rwth-aachen.de/",
      aliases: ["RWTH"],
    },
    {
      id: "university-tum",
      name: "Technical University of Munich",
      countryCode: "DE",
      websiteUrl: "https://www.tum.de/en/",
      aliases: ["TUM"],
    },
    {
      id: "university-dtu",
      name: "Technical University of Denmark",
      countryCode: "DK",
      websiteUrl: "https://www.dtu.dk/english/",
      aliases: ["DTU"],
    },
    {
      id: "university-aalto",
      name: "Aalto University",
      countryCode: "FI",
      websiteUrl: "https://www.aalto.fi/en",
    },
    {
      id: "university-imperial",
      name: "Imperial College London",
      countryCode: "GB",
      websiteUrl: "https://www.imperial.ac.uk/",
      aliases: ["Imperial"],
    },
    {
      id: "university-edinburgh",
      name: "The University of Edinburgh",
      countryCode: "GB",
      websiteUrl: "https://www.ed.ac.uk/",
      aliases: ["Edinburgh"],
    },
    {
      id: "university-ucl",
      name: "University College London",
      countryCode: "GB",
      websiteUrl: "https://www.ucl.ac.uk/",
      aliases: ["UCL"],
    },
    {
      id: "university-polimi",
      name: "Politecnico di Milano",
      countryCode: "IT",
      websiteUrl: "https://www.polimi.it/en/",
      aliases: ["Polimi"],
    },
    {
      id: "university-tu-delft",
      name: "Delft University of Technology",
      countryCode: "NL",
      websiteUrl: "https://www.tudelft.nl/en/",
      aliases: ["TU Delft"],
    },
    {
      id: "university-amsterdam",
      name: "University of Amsterdam",
      countryCode: "NL",
      websiteUrl: "https://www.uva.nl/en/",
      aliases: ["UvA"],
    },
    {
      id: "university-kth",
      name: "KTH Royal Institute of Technology",
      countryCode: "SE",
      websiteUrl: "https://www.kth.se/en",
      aliases: ["KTH"],
    },
    {
      id: "university-chulalongkorn",
      name: "Chulalongkorn University",
      countryCode: "TH",
      websiteUrl: "https://www.chula.ac.th/",
      aliases: ["Chula"],
    },
    {
      id: "university-kmutt",
      name: "King Mongkut's University of Technology Thonburi",
      countryCode: "TH",
      websiteUrl: "https://www.kmutt.ac.th/",
      aliases: ["KMUTT"],
    },
    {
      id: "university-mahidol",
      name: "Mahidol University",
      countryCode: "TH",
      websiteUrl: "https://www.mahidol.ac.th/",
    },
    {
      id: "university-carnegie-mellon",
      name: "Carnegie Mellon University",
      countryCode: "US",
      websiteUrl: "https://www.cmu.edu/",
      aliases: ["CMU"],
    },
    {
      id: "university-cornell",
      name: "Cornell University",
      countryCode: "US",
      websiteUrl: "https://www.cornell.edu/",
    },
    {
      id: "university-georgia-tech",
      name: "Georgia Institute of Technology",
      countryCode: "US",
      websiteUrl: "https://www.gatech.edu/",
      aliases: ["Georgia Tech"],
    },
    {
      id: "university-mit",
      name: "Massachusetts Institute of Technology",
      countryCode: "US",
      websiteUrl: "https://www.mit.edu/",
      aliases: ["MIT"],
    },
    {
      id: "university-stanford",
      name: "Stanford University",
      countryCode: "US",
      websiteUrl: "https://www.stanford.edu/",
    },
    {
      id: "university-berkeley",
      name: "University of California, Berkeley",
      countryCode: "US",
      websiteUrl: "https://www.berkeley.edu/",
      aliases: ["UC Berkeley", "Berkeley"],
    },
    {
      id: "university-ucsd",
      name: "University of California San Diego",
      countryCode: "US",
      websiteUrl: "https://ucsd.edu/",
      aliases: ["UC San Diego", "UCSD"],
    },
    {
      id: "university-uiuc",
      name: "University of Illinois Urbana-Champaign",
      countryCode: "US",
      websiteUrl: "https://illinois.edu/",
      aliases: ["UIUC", "Illinois"],
    },
    {
      id: "university-michigan",
      name: "University of Michigan–Ann Arbor",
      countryCode: "US",
      websiteUrl: "https://umich.edu/",
      aliases: ["UMich", "Michigan"],
    },
    {
      id: "university-washington",
      name: "University of Washington, Seattle",
      countryCode: "US",
      websiteUrl: "https://www.washington.edu/",
      aliases: ["UW Seattle"],
    },
  ],
  programs: [
    {
      id: "program-ku-leuven-artificial-intelligence-master",
      universityId: "university-ku-leuven",
      name: "Master of Artificial Intelligence",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://www.kuleuven.be/opleidingen/programmes/master-artificial-intelligence",
    },
    {
      id: "program-mcgill-computer-science-bsc",
      universityId: "university-mcgill",
      name: "B.Sc. Major in Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.cs.mcgill.ca/academic/undergrad/bsc/",
    },
    {
      id: "program-mcgill-computer-science-msc-non-thesis",
      universityId: "university-mcgill",
      name: "M.Sc. Computer Science (Non-Thesis)",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.mcgill.ca/gradapplicants/program/computer-science-msc-non-thesis",
    },
    {
      id: "program-alberta-computing-science-multimedia-msc",
      universityId: "university-alberta",
      name: "Master of Science (Course-Based) in Computing Science, Multimedia",
      degreeLevel: "master",
      subjectArea: "Computing Science",
      officialUrl: "https://www.gsa.ualberta.ca/en/computing-science/graduate-studies/programs-and-admissions/multimedia.html",
      aliases: ["Multimedia M.Sc."],
    },
    {
      id: "program-ubc-computer-science-bsc",
      universityId: "university-ubc",
      name: "Computer Science Major (BSc)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.cs.ubc.ca/students/undergrad/degree-programs",
    },
    {
      id: "program-ubc-computer-science-msc",
      universityId: "university-ubc",
      name: "MSc Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.cs.ubc.ca/students/grad/graduate-programs/msc-program",
    },
    {
      id: "program-toronto-computer-science-st-george-bsc",
      universityId: "university-toronto",
      name: "Computer Science Admission Category (St. George)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.artsci.utoronto.ca/future/ready-apply/admission-categories/computer-science",
      aliases: ["Computer Science St. George"],
    },
    {
      id: "program-toronto-mscac-artificial-intelligence",
      universityId: "university-toronto",
      name: "Applied Computing MScAC — Artificial Intelligence Concentration",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://mscac.utoronto.ca/concentrations/ai/",
      aliases: ["MScAC Artificial Intelligence"],
    },
    {
      id: "program-waterloo-computer-science-bcs",
      universityId: "university-waterloo",
      name: "Bachelor of Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://uwaterloo.ca/future-students/programs/computer-science",
      aliases: ["BCS Computer Science"],
    },
    {
      id: "program-waterloo-computer-science-mmath",
      universityId: "university-waterloo",
      name: "Master of Mathematics (Computer Science)",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://uwaterloo.ca/computer-science/current-graduate-students/overview-degree-programs/master-mathematics-computer-science",
      aliases: ["MMath Computer Science"],
    },
    {
      id: "program-rwth-aachen-data-science-msc",
      universityId: "university-rwth-aachen",
      name: "Data Science M.Sc.",
      degreeLevel: "master",
      subjectArea: "Data Science",
      officialUrl: "https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/",
    },
    {
      id: "program-rwth-aachen-human-centered-intelligent-systems-msc",
      universityId: "university-rwth-aachen",
      name: "Human-Centered Intelligent Systems M.Sc.",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://sc.informatik.rwth-aachen.de/en/studium/master/master-hcis/",
      aliases: ["HCIS"],
    },
    {
      id: "program-tum-informatics-msc",
      universityId: "university-tum",
      name: "Informatics M.Sc.",
      degreeLevel: "master",
      subjectArea: "Informatics",
      officialUrl: "https://www.cit.tum.de/en/cit/studies/degree-programs/master-informatics/",
    },
    {
      id: "program-dtu-computer-science-engineering-msc",
      universityId: "university-dtu",
      name: "Master of Science in Engineering (Computer Science and Engineering)",
      degreeLevel: "master",
      subjectArea: "Computer Science and Engineering",
      officialUrl: "https://www.dtu.dk/english/education/graduate/msc-programmes/computer-science-and-engineering",
    },
    {
      id: "program-aalto-machine-learning-data-science-artificial-intelligence-msc",
      universityId: "university-aalto",
      name: "Machine Learning, Data Science and Artificial Intelligence, Master of Science (Technology)",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence and Data Science",
      officialUrl: "https://www.aalto.fi/en/study-options/machine-learning-data-science-and-artificial-intelligence-master-of-science-technology",
      aliases: ["Machine Learning Data Science and Artificial Intelligence"],
    },
    {
      id: "program-imperial-computing-beng",
      universityId: "university-imperial",
      name: "Computing BEng",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.imperial.ac.uk/study/courses/undergraduate/computing-beng/",
    },
    {
      id: "program-edinburgh-artificial-intelligence-bsc",
      universityId: "university-edinburgh",
      name: "Artificial Intelligence BSc (Hons)",
      degreeLevel: "bachelor",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://study.ed.ac.uk/programmes/undergraduate/388-artificial-intelligence",
    },
    {
      id: "program-edinburgh-artificial-intelligence-msc",
      universityId: "university-edinburgh",
      name: "Artificial Intelligence MSc",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://study.ed.ac.uk/programmes/postgraduate-taught/107-artificial-intelligence",
    },
    {
      id: "program-ucl-computer-science-bsc",
      universityId: "university-ucl",
      name: "Computer Science BSc",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.ucl.ac.uk/study/prospective-students/undergraduate/courses/computer-science-bsc",
    },
    {
      id: "program-polimi-computer-science-engineering-msc",
      universityId: "university-polimi",
      name: "Computer Science and Engineering",
      degreeLevel: "master",
      subjectArea: "Computer Science and Engineering",
      officialUrl: "https://www.polimi.it/en/education/laurea-magistrale-programmes/programme-detail/computer-science-and-engineering",
      aliases: ["MSc Computer Science and Engineering"],
    },
    {
      id: "program-tu-delft-computer-science-msc",
      universityId: "university-tu-delft",
      name: "MSc Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.tudelft.nl/onderwijs/opleidingen/masters/cs/msc-computer-science/",
    },
    {
      id: "program-amsterdam-artificial-intelligence-msc",
      universityId: "university-amsterdam",
      name: "MSc Artificial Intelligence",
      degreeLevel: "master",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://www.uva.nl/shared-content/programmas/en/masters/artificial-intelligence/artificial-intelligence.html",
    },
    {
      id: "program-kth-computer-science-msc",
      universityId: "university-kth",
      name: "MSc Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.kth.se/en/studies/master/computer-science",
    },
    {
      id: "program-chulalongkorn-computer-engineering-beng",
      universityId: "university-chulalongkorn",
      name: "Bachelor of Engineering: Computer Engineering (CP)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Engineering",
      officialUrl: "https://www.cp.eng.chula.ac.th/en/prospective/bachelor",
    },
    {
      id: "program-chulalongkorn-csit-msc",
      universityId: "university-chulalongkorn",
      name: "Master of Science Program in Computer Science and Information Technology",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.chula.ac.th/program/computer-science-and-information-technology",
    },
    {
      id: "program-kmutt-computer-science-bsc",
      universityId: "university-kmutt",
      name: "Bachelor of Science in Computer Science (English Program)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.sit.kmutt.ac.th/en/bsc/bsc-cs-2",
    },
    {
      id: "program-kmutt-computer-science-msc",
      universityId: "university-kmutt",
      name: "Master of Science in Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.sit.kmutt.ac.th/en/msc/msc-cs",
    },
    {
      id: "program-mahidol-computer-science-msc",
      universityId: "university-mahidol",
      name: "Master of Science in Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://www.ict.mahidol.ac.th/en/programs/comscience",
    },
    {
      id: "program-cmu-artificial-intelligence-bs",
      universityId: "university-carnegie-mellon",
      name: "Bachelor of Science in Artificial Intelligence",
      degreeLevel: "bachelor",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://www.cs.cmu.edu/bs-in-artificial-intelligence/",
    },
    {
      id: "program-cmu-computer-science-bs",
      universityId: "university-carnegie-mellon",
      name: "Bachelor of Science in Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.csd.cmu.edu/academics/bachelors/overview",
    },
    {
      id: "program-cornell-computer-science-bs",
      universityId: "university-cornell",
      name: "Computer Science, B.S. (Engineering)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://catalog.cornell.edu/programs/computer-science-bs/",
    },
    {
      id: "program-cornell-computer-science-meng",
      universityId: "university-cornell",
      name: "Computer Science, M.Eng.",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://catalog.cornell.edu/programs/computer-science-cscn-meng/",
    },
    {
      id: "program-georgia-tech-computer-science-bs",
      universityId: "university-georgia-tech",
      name: "Bachelor of Science in Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://catalog.gatech.edu/programs/computer-science-bs",
    },
    {
      id: "program-mit-artificial-intelligence-decision-making-bs",
      universityId: "university-mit",
      name: "Bachelor of Science in Artificial Intelligence and Decision Making (Course 6-4)",
      degreeLevel: "bachelor",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://catalog.mit.edu/schools/mit-schwarzman-college-computing/electrical-engineering-computer-science/",
    },
    {
      id: "program-mit-computer-science-engineering-bs",
      universityId: "university-mit",
      name: "Bachelor of Science in Computer Science and Engineering (Course 6-3)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://catalog.mit.edu/schools/mit-schwarzman-college-computing/electrical-engineering-computer-science/",
    },
    {
      id: "program-stanford-computer-science-bs",
      universityId: "university-stanford",
      name: "Computer Science Bachelor's Program",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.cs.stanford.edu/academics-overview/academics-bachelors-program",
    },
    {
      id: "program-berkeley-computer-science-ba",
      universityId: "university-berkeley",
      name: "Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://undergraduate.catalog.berkeley.edu/programs/A5201U",
    },
    {
      id: "program-ucsd-artificial-intelligence-bs",
      universityId: "university-ucsd",
      name: "B.S. Artificial Intelligence",
      degreeLevel: "bachelor",
      subjectArea: "Artificial Intelligence",
      officialUrl: "https://cse.ucsd.edu/undergraduate/bs-artificial-intelligence-cse-bs-004",
    },
    {
      id: "program-ucsd-computer-science-bs",
      universityId: "university-ucsd",
      name: "B.S. Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://cse.ucsd.edu/undergraduate/bs-computer-science-cse-bs-002",
    },
    {
      id: "program-ucsd-computer-science-ms",
      universityId: "university-ucsd",
      name: "M.S. Computer Science",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://cse.ucsd.edu/graduate/degree-programs/ms-program",
    },
    {
      id: "program-uiuc-computer-science-bs",
      universityId: "university-uiuc",
      name: "B.S. in Computer Science",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://siebelschool.illinois.edu/academics/undergraduate/degree-program-options/bs-computer-science",
    },
    {
      id: "program-uiuc-computer-science-mcs",
      universityId: "university-uiuc",
      name: "Master of Computer Science in Urbana-Champaign",
      degreeLevel: "master",
      subjectArea: "Computer Science",
      officialUrl: "https://siebelschool.illinois.edu/academics/graduate/professional-mcs/campus-master-computer-science",
      aliases: ["MCS Urbana-Champaign"],
    },
    {
      id: "program-michigan-computer-science-engineering-bs",
      universityId: "university-michigan",
      name: "Computer Science Major (Engineering)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://cse.engin.umich.edu/academics/undergraduate/majors/computer-science-eng-major/",
      aliases: ["CS-Eng"],
    },
    {
      id: "program-michigan-computer-science-engineering-ms",
      universityId: "university-michigan",
      name: "Master's in Computer Science and Engineering",
      degreeLevel: "master",
      subjectArea: "Computer Science and Engineering",
      officialUrl: "https://cse.engin.umich.edu/academics/graduate/graduate-programs/masters-in-cse/",
    },
    {
      id: "program-washington-computer-science-bs",
      universityId: "university-washington",
      name: "B.S. Computer Science (Seattle)",
      degreeLevel: "bachelor",
      subjectArea: "Computer Science",
      officialUrl: "https://www.cs.washington.edu/academics/undergraduate/admissions/",
    },
  ],
} as const;

export const researchCatalog = researchCatalogSchema.parse(rawCatalog);
